# Generated by Django 4.2.1 on 2023-06-08 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 1, 15, 1, 349532, tzinfo=datetime.timezone.utc)),
        ),
    ]
