# Generated by Django 4.2.1 on 2023-06-12 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 0, 52, 53, 444734, tzinfo=datetime.timezone.utc)),
        ),
    ]
